linters:
  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
    # Disable
    # - sql
    # - complexity
  disable:
    - wsl
    - gomnd
  enable:
    - gosimple
    - unconvert
linters-settings:
  godot:
    exclude:
      - ;$
  forbidigo:
    forbid:
      - ^print.*$
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/takoeight0821/anma
          - github.com/google/go-cmp/cmp
          - github.com/peterh/liner
          - github.com/adrg/xdg
  exhaustruct:
    include:
      - '.*\.<anonymous>'
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - Node
      - Value
      - Sexp
  varnamelen:
    ignore-decls:
      - i int