linters:
  presets:
    - bugs
    # - comment
    - error
    # - format
    - import
    # - metalinter
    - module
    - performance
    # - style
    - test
    - unused
    # Disable
    # - sql
    # - complexity
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/takoeight0821/anma
          - github.com/google/go-cmp/cmp
          - github.com/peterh/liner
          - github.com/adrg/xdg
  exhaustruct:
    include:
      - '.*\.<anonymous>'