// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[LEFT_BRACKET-5]
	_ = x[RIGHT_BRACKET-6]
	_ = x[COLON-7]
	_ = x[COMMA-8]
	_ = x[DOT-9]
	_ = x[SEMICOLON-10]
	_ = x[SHARP-11]
	_ = x[IDENT-12]
	_ = x[OPERATOR-13]
	_ = x[INTEGER-14]
	_ = x[STRING-15]
	_ = x[TYPE-16]
	_ = x[DEF-17]
	_ = x[CASE-18]
}

const _TokenKind_name = "EOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETCOLONCOMMADOTSEMICOLONSHARPIDENTOPERATORINTEGERSTRINGTYPEDEFCASE"

var _TokenKind_index = [...]uint8{0, 3, 13, 24, 34, 45, 57, 70, 75, 80, 83, 92, 97, 102, 110, 117, 123, 127, 130, 134}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
