// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[LEFT_PAREN-1]
	_ = x[RIGHT_PAREN-2]
	_ = x[LEFT_BRACE-3]
	_ = x[RIGHT_BRACE-4]
	_ = x[LEFT_BRACKET-5]
	_ = x[RIGHT_BRACKET-6]
	_ = x[COLON-7]
	_ = x[COMMA-8]
	_ = x[DOT-9]
	_ = x[SEMICOLON-10]
	_ = x[SHARP-11]
	_ = x[IDENT-12]
	_ = x[OPERATOR-13]
	_ = x[INTEGER-14]
	_ = x[STRING-15]
	_ = x[ARROW-16]
	_ = x[CASE-17]
	_ = x[DEF-18]
	_ = x[EQUAL-19]
	_ = x[FN-20]
	_ = x[LET-21]
	_ = x[TYPE-22]
}

const _Kind_name = "EOFLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACELEFT_BRACKETRIGHT_BRACKETCOLONCOMMADOTSEMICOLONSHARPIDENTOPERATORINTEGERSTRINGARROWCASEDEFEQUALFNLETTYPE"

var _Kind_index = [...]uint8{0, 3, 13, 24, 34, 45, 57, 70, 75, 80, 83, 92, 97, 102, 110, 117, 123, 128, 132, 135, 140, 142, 145, 149}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
